camunda:
  dmn:
    decision-key: Decision_0ozg60u
    file-location: loan-request-filter-starter/src/main/resources/camunda/diagram.dmn
  enabled: false

elasticsearch:
  connection-timeout: 10s
  enabled: false
  url: http://localhost:9200
