package com.github.sawafrolov.loanrequestfilter.filterservice.repositories

import com.github.sawafrolov.loanrequestfilter.commons.documents.LoanRequestDocument
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository
import org.springframework.stereotype.Repository

@Repository
interface ElasticSearchLoanRequestRepository: ElasticsearchRepository<LoanRequestDocument, String>
